### ISSUE TITLE
About the cookie not clearing properly when a post is submitted

### ISSUE THREAD

**Issue by Tester21981** [GerB/modernquote#7]
I've just found out that it's to do with quick reply. If I disable quick reply, the cookie clears fine and the button does not reappear in the corner when a post is submitted. But if I enable quick reply, it does, and I have to click the little bin icon to make it disappear.

**Comment by GerB** [comment]
https://www.phpbb.com/customise/db/extension/modern_quote/support/topic/224551?p=866125#p866125
